"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
require("../extension/protocol.js");require("../extension/adapter.js");
function fixture(){
 let now=100000,seq=0;
 const tabs=new Map([[10,{id:10,windowId:1,title:"Video",url:"https://www.youtube.com/watch?v=test",active:true,status:"complete"}],
 [11,{id:11,windowId:1,title:"Stremio",url:"https://web.stremio.com/",active:false,status:"complete"}],
 [12,{id:12,windowId:2,title:"Other",url:"https://example.com/",active:true,status:"complete"}]]);
 const updates=[],grants=new Set(["https://www.youtube.com/*","https://web.stremio.com/*"]);
 const windows=[{id:1,type:"normal",incognito:false,left:0,top:0,width:1280,height:720},{id:2,type:"normal",incognito:false,left:1280,top:0,width:900,height:700}];
 const api={windows:{get:async id=>({...windows.find(w=>w.id===id)}),getAll:async()=>windows.map(w=>({...w}))},
 tabs:{get:async id=>{if(!tabs.has(id))throw Error("missing tab");return {...tabs.get(id)};},query:async({windowId})=>[...tabs.values()].filter(t=>t.windowId===windowId).map(t=>({...t})),
 update:async(id,data)=>{updates.push({id,data});if(data.active)for(const t of tabs.values())if(t.windowId===tabs.get(id).windowId)t.active=false;Object.assign(tabs.get(id),data);return {...tabs.get(id)};}},
 permissions:{contains:async({origins})=>origins.every(o=>grants.has(o))},
 scripting:{executeScript:async()=>{throw Error("unexpected script call");}}};
 const adapter=new BWCZenAdapter(api,{now:()=>now,uuid:()=>"id-"+(++seq)});
 const request=(op,args={},epoch=1)=>({v:1,id:"request-"+(++seq),sessionId:"session-one",epoch,deadlineUnixMs:now+10000,op,args});
 const bind=async(epoch=1)=>{const pair=adapter.pair(1);return adapter.dispatch(request("bind",{windowId:1,pairingNonce:pair.pairingNonce},epoch));};
 return {adapter,api,tabs,windows,updates,grants,request,bind,advance:n=>now+=n};
}
test("capability claims are semantic only",async()=>{const f=fixture();const c=await f.adapter.dispatch(f.request("capabilities"));assert.equal(c.trustedPointerKeyboard,false);assert.equal(c.drag,false);assert.equal(c.fileInput,false);});
test("binding needs real unexpired pairing and unique window",async()=>{const f=fixture();await assert.rejects(f.adapter.dispatch(f.request("bind",{windowId:1,pairingNonce:"invented"})),/pairing_required/);await f.bind();await assert.rejects(f.bind(),/window_already_bound/);});
test("a new candidate nonce invalidates the previous nonce for that window",async()=>{const f=fixture();const old=f.adapter.pair(1),fresh=f.adapter.pair(1);await assert.rejects(f.adapter.dispatch(f.request("bind",{windowId:1,pairingNonce:old.pairingNonce})),/pairing_required/);assert.equal((await f.adapter.dispatch(f.request("bind",{windowId:1,pairingNonce:fresh.pairingNonce}))).bound,true);});
test("tab selection verifies actual active tab and never requests window focus",async()=>{const f=fixture();await f.bind();const o=await f.adapter.dispatch(f.request("observe"));const a=await f.adapter.dispatch(f.request("input",{observationId:o.observationId,action:"select_tab",tabId:11}));assert.equal(a.effectVerified,false);const v=await f.adapter.dispatch(f.request("verify",{actionId:a.actionId}));assert.equal(v.effectVerified,true);assert.deepEqual(f.updates,[{id:11,data:{active:true}}]);assert.equal(f.tabs.get(10).active,false);});
test("foreign tab and navigation after observation are rejected",async()=>{const f=fixture();await f.bind();const o=await f.adapter.dispatch(f.request("observe"));await assert.rejects(f.adapter.dispatch(f.request("input",{observationId:o.observationId,action:"select_tab",tabId:12})),/tab_out_of_scope/);f.tabs.get(11).url="https://changed.example/";await assert.rejects(f.adapter.dispatch(f.request("input",{observationId:o.observationId,action:"select_tab",tabId:11})),/tab_changed/);assert.equal(f.updates.length,0);});
test("navigation requires target host grant and refuses privileged URLs",async()=>{const f=fixture();await f.bind();let o=await f.adapter.dispatch(f.request("observe"));await assert.rejects(f.adapter.dispatch(f.request("input",{observationId:o.observationId,action:"navigate",url:"javascript:alert(1)"})),/unsupported_url/);o=await f.adapter.dispatch(f.request("observe"));await assert.rejects(f.adapter.dispatch(f.request("input",{observationId:o.observationId,action:"navigate",url:"https://ungranted.example/"})),/site_permission_required/);o=await f.adapter.dispatch(f.request("observe"));const a=await f.adapter.dispatch(f.request("input",{observationId:o.observationId,action:"navigate",url:"https://web.stremio.com/"}));assert.equal((await f.adapter.dispatch(f.request("verify",{actionId:a.actionId}))).effectVerified,true);});
test("Pause invalidates observation, Resume needs new observation, Stop requires new pairing epoch",async()=>{const f=fixture();await f.bind();const o=await f.adapter.dispatch(f.request("observe"));await f.adapter.dispatch(f.request("pause"));await assert.rejects(f.adapter.dispatch(f.request("input",{observationId:o.observationId,action:"select_tab",tabId:11})),/stale_observation/);await f.adapter.dispatch(f.request("resume"));await assert.rejects(f.adapter.dispatch(f.request("input",{observationId:o.observationId,action:"select_tab",tabId:11})),/stale_observation/);await f.adapter.dispatch(f.request("stop"));await assert.rejects(f.bind(),/stale_epoch/);await f.bind(2);});
test("Stop revokes action waiting at an async browser read",async()=>{const f=fixture();await f.bind();const o=await f.adapter.dispatch(f.request("observe"));let release;const original=f.api.tabs.get;f.api.tabs.get=id=>new Promise(resolve=>{release=()=>original(id).then(resolve);});const action=f.adapter.dispatch(f.request("input",{observationId:o.observationId,action:"select_tab",tabId:11}));await new Promise(r=>setImmediate(r));await f.adapter.dispatch(f.request("stop"));release();await assert.rejects(action,/session_revoked/);assert.equal(f.updates.length,0);});
test("Stop cancels binding queued in browser API",async()=>{const f=fixture();let release;f.api.windows.get=id=>new Promise(resolve=>{release=()=>resolve({...f.windows.find(w=>w.id===id)});});const binding=f.bind();await new Promise(r=>setImmediate(r));await f.adapter.dispatch(f.request("stop"));release();await assert.rejects(binding,/binding_revoked/);assert.equal(f.adapter.sessions.size,0);});
test("expired deadline and unknown request fields fail closed",async()=>{const f=fixture();let r=f.request("capabilities");f.advance(10001);assert.throws(()=>f.adapter.dispatch(r),/expired/);assert.throws(()=>f.adapter.dispatch({...f.request("capabilities"),evaluate:"code"}),/unknown_argument/);});
test("protected and private targets are excluded",async()=>{const f=fixture();await f.bind();f.tabs.get(10).title="Sign in";await assert.rejects(f.adapter.dispatch(f.request("observe")),/protected_page/);f.tabs.get(10).title="normal";f.tabs.get(10).incognito=true;await assert.rejects(f.adapter.dispatch(f.request("observe",{tabId:10})),/tab_out_of_scope/);});
test("explicit candidate request enumerates all normal public windows once without reading tabs or content",async()=>{const f=fixture();f.windows.push({...f.windows[0]}, {...f.windows[0],id:3,incognito:true}, {...f.windows[0],id:4,type:"popup"});f.api.tabs.query=async()=>{throw Error("must not inspect tabs");};const result=await f.adapter.dispatch(f.request("pair_candidates"));assert.deepEqual(result.candidates.map(c=>c.windowId),[1,2]);assert.equal(new Set(result.candidates.map(c=>c.pairingNonce)).size,2);assert.ok(result.candidates.every(c=>c.expiresAt===130000 && c.window.incognito===false));assert.deepEqual(Object.keys(result.candidates[0].window),["id","left","top","width","height","type","incognito"]);assert.equal(f.adapter.sessions.size,0);});
test("bind reports newly read geometry and consumes candidate nonce",async()=>{const f=fixture();const {candidates}=await f.adapter.dispatch(f.request("pair_candidates"));f.windows[0].left=50;const result=await f.adapter.dispatch(f.request("bind",{windowId:1,pairingNonce:candidates[0].pairingNonce}));assert.equal(result.window.left,50);assert.equal(f.adapter.pairings.has(candidates[0].pairingNonce),false);});
test("candidate nonce expiry and malformed geometry fail closed",async()=>{const f=fixture();const {candidates}=await f.adapter.dispatch(f.request("pair_candidates"));f.advance(30000);await assert.rejects(f.adapter.dispatch(f.request("bind",{windowId:1,pairingNonce:candidates[0].pairingNonce})),/pairing_required/);f.windows[0].width=NaN;await assert.rejects(f.adapter.dispatch(f.request("pair_candidates")),/window_geometry_unavailable/);});
test("disconnect invalidates queued candidate and bind requests, allows fresh generation",async()=>{const f=fixture();let release;f.api.windows.getAll=()=>new Promise(resolve=>{release=()=>resolve(f.windows);});const active=f.adapter.dispatch(f.request("pair_candidates"));const queued=f.adapter.dispatch(f.request("pair_candidates"));const checkActive=assert.rejects(active,/binding_revoked/),checkQueued=assert.rejects(queued,/connection_revoked/);await new Promise(r=>setImmediate(r));f.adapter.disconnect();f.api.windows.getAll=async()=>f.windows;const fresh=await f.adapter.dispatch(f.request("pair_candidates"));assert.equal(fresh.candidates.length,2);release();await Promise.all([checkActive,checkQueued]);assert.equal(f.adapter.pairings.size,2);});
test("disconnect during bind browser read cannot bind after reconnect",async()=>{const f=fixture();let release;const original=f.api.windows.get;f.api.windows.get=id=>new Promise(resolve=>{release=()=>original(id).then(resolve);});const active=f.bind();const checked=assert.rejects(active,/binding_revoked/);await new Promise(r=>setImmediate(r));f.adapter.disconnect();f.api.windows.get=original;await f.bind();release();await checked;assert.equal(f.adapter.sessions.size,1);});
