"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function event(){const listeners=[];return {listeners,addListener:fn=>listeners.push(fn),emit:(...args)=>Promise.all(listeners.map(fn=>fn(...args)))};}
async function fixture(saved={}){
 const data=saved,ports=[],timers=new Map(),calls={windowReads:0,tabReads:0,grants:[],badges:[]};let timerId=0,uuid=0,requestId=0;
 const windows=[{id:1,left:10,top:20,width:1000,height:800,type:"normal",incognito:false}];
 const browser={runtime:{onStartup:event(),onMessage:event(),getManifest:()=>({version:"0.2.0"}),getURL:file=>"moz-extension://test-id/"+file,connectNative:()=>{const port={onMessage:event(),onDisconnect:event(),sent:[],closed:false,postMessage(message){if(this.closed)throw Error("closed");this.sent.push(message);},disconnect(){this.closed=true;return this.onDisconnect.emit();}};ports.push(port);return port;}},
 storage:{local:{get:async key=>typeof key==="string"?{[key]:data[key]}:{...data},set:async value=>Object.assign(data,value)}},
 action:{onClicked:event(),setBadgeText:async value=>calls.badges.push(value.text),setTitle:async()=>{}},
 windows:{onRemoved:event(),getAll:async()=>{calls.windowReads++;return windows.map(w=>({...w}));},get:async id=>{calls.windowReads++;return {...windows.find(w=>w.id===id)};}},
 tabs:{query:async()=>{calls.tabReads++;return [];}},
 permissions:{onRemoved:event(),request:async options=>{calls.grants.push(options);return true;},contains:async()=>true}};
 const context=vm.createContext({browser,crypto:{randomUUID:()=>"nonce-"+(++uuid)},Date,URL,console,Promise,setTimeout:(fn,delay)=>{const id=++timerId;timers.set(id,{fn,delay});return id;},clearTimeout:id=>timers.delete(id)});
 for(const file of ["protocol.js","adapter.js","background.js"])vm.runInContext(fs.readFileSync(path.join(__dirname,"../extension",file),"utf8"),context,{filename:file});
 await tick();
 const request=(op,args={},sessionId="session-one",epoch=1)=>({v:1,id:"request-"+(++requestId),sessionId,epoch,deadlineUnixMs:Date.now()+10000,op,args});
 const transport=(state,port=ports.at(-1))=>port.onMessage.emit({v:1,type:"transport",state});
 const ask=async(op,args={},sessionId="session-one",epoch=1)=>{const port=ports.at(-1),r=request(op,args,sessionId,epoch);await port.onMessage.emit(r);return port.sent.find(m=>m.id===r.id);};
 const local=message=>browser.runtime.onMessage.emit(message,{id:"zen-companion@betterwincontrol.local",url:browser.runtime.getURL("options.html"),tab:{id:500},frameId:0});
 const bind=async(sessionId="session-one")=>{const reply=await ask("pair_candidates",{},sessionId);return ask("bind",{windowId:1,pairingNonce:reply.result.candidates[0].pairingNonce},sessionId);};
 const retry=async()=>{assert.equal(timers.size,1);const [id,item]=timers.entries().next().value;timers.delete(id);item.fn();await tick();return item.delay;};
 return {browser,data,ports,timers,calls,transport,ask,local,bind,request,retry,windows};
}
test("startup opens one native port without toolbar, tab reads or permission requests",async()=>{const f=await fixture();assert.equal(f.ports.length,1);assert.equal(f.ports[0].sent[0].type,"hello");assert.equal(f.ports[0].sent[0].version,"0.2.0");assert.equal(f.calls.windowReads,0);assert.equal(f.calls.tabReads,0);assert.equal(f.calls.grants.length,0);await f.browser.runtime.onStartup.emit();assert.equal(f.ports.length,1);await f.transport("waiting");assert.equal(f.data.phase,"ready");});
test("transport authentication precedes candidate requests; bind works without gesture",async()=>{const f=await fixture();assert.equal(await f.ask("pair_candidates"),undefined);await f.transport("connected");const binding=await f.bind();assert.equal(binding.result.bound,true);assert.equal(f.data.phase,"connected");assert.equal(f.calls.grants.length,0);});
test("core Stop leaves readiness enabled for next explicit session",async()=>{const f=await fixture();await f.transport("connected");await f.bind();const result=await f.ask("stop");assert.equal(result.result.stopped,true);assert.equal(f.data.readinessEnabled,true);assert.equal(f.data.phase,"ready");assert.equal(f.ports.length,1);assert.equal((await f.bind("session-two")).result.bound,true);});
test("broker disconnect revokes old session and nonces but keeps native port ready",async()=>{const f=await fixture();await f.transport("connected");await f.bind();const fresh=await f.ask("pair_candidates");await f.transport("waiting");await f.transport("connected");assert.match((await f.ask("observe")).error.code,/revoked/);assert.equal((await f.ask("bind",{windowId:1,pairingNonce:fresh.result.candidates[0].pairingNonce})).error.code,"pairing_required");assert.equal(f.ports.length,1);assert.equal((await f.bind("session-two")).result.bound,true);});
test("helper crash reconnects with bounded backoff and no gestures",async()=>{const f=await fixture();const delays=[];for(let i=0;i<8;i++){await f.ports.at(-1).onDisconnect.emit();delays.push(await f.retry());}assert.deepEqual(delays,[250,500,1000,2000,5000,10000,10000,10000]);assert.equal(f.ports.length,9);assert.equal(f.calls.tabReads,0);await f.transport("waiting");await f.ports.at(-1).onDisconnect.emit();assert.equal(await f.retry(),250);});
test("explicit disable survives restart, suppresses crash reconnect, and re-enables only locally",async()=>{const f=await fixture();await f.transport("connected");await f.bind();await f.local({type:"disable_readiness"});assert.equal(f.data.readinessEnabled,false);assert.equal(f.ports[0].closed,true);assert.ok(f.ports[0].sent.some(m=>m.event==="user_stop"));assert.equal(f.timers.size,0);const restarted=await fixture({...f.data});assert.equal(restarted.ports.length,0);await restarted.browser.runtime.onStartup.emit();assert.equal(restarted.ports.length,0);await restarted.local({type:"enable_readiness"});assert.equal(restarted.ports.length,1);assert.equal(restarted.data.readinessEnabled,true);});
test("content scripts and unrelated senders cannot enable readiness",async()=>{const f=await fixture({readinessEnabled:false});await f.browser.runtime.onMessage.emit({type:"enable_readiness"},{id:"other"});await f.browser.runtime.onMessage.emit({type:"enable_readiness"},{id:"zen-companion@betterwincontrol.local",tab:{id:10}});assert.equal(f.ports.length,0);});
test("pending old bind reply is discarded after transport turnover",async()=>{const f=await fixture();await f.transport("connected");const candidates=await f.ask("pair_candidates");let release;const original=f.browser.windows.get;f.browser.windows.get=id=>new Promise(resolve=>{release=()=>original(id).then(resolve);});const request=f.request("bind",{windowId:1,pairingNonce:candidates.result.candidates[0].pairingNonce});const pending=f.ports[0].onMessage.emit(request);await tick();await f.transport("waiting");await f.transport("connected");f.browser.windows.get=original;assert.equal((await f.bind("fresh-session")).result.bound,true);release();await pending;assert.equal(f.ports[0].sent.some(m=>m.id===request.id),false);assert.equal(f.data.phase,"connected");});
test("optional toolbar grant enables readiness without emitting legacy pairing event",async()=>{const f=await fixture({readinessEnabled:false});await f.browser.action.onClicked.emit({id:10,windowId:1,url:"https://web.stremio.com/",incognito:false});assert.equal(f.ports.length,1);assert.equal(f.calls.grants[0].origins[0],"https://web.stremio.com/*");assert.equal(f.ports[0].sent.some(m=>m.event==="pair_requested"),false);const privateFixture=await fixture({readinessEnabled:false});await privateFixture.browser.action.onClicked.emit({id:10,windowId:1,url:"https://example.com/",incognito:true});assert.equal(privateFixture.calls.grants.length,0);assert.equal(privateFixture.ports.length,0);});
