"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto");
const {JSDOM}=require("jsdom");
function fixture(html='<input type="text" aria-label="Notes"><button aria-label="Apply">Apply</button><video aria-label="Movie"></video>'){
 const dom=new JSDOM('<!doctype html><title>Fixture</title>'+html,{url:"https://fixture.example/",runScripts:"outside-only"});
 const w=dom.window;w.crypto.randomUUID=crypto.randomUUID;
 w.HTMLElement.prototype.getBoundingClientRect=function(){return {x:10,y:10,left:10,top:10,right:110,bottom:40,width:100,height:30};};
 Object.defineProperty(w.document,"scrollingElement",{value:w.document.documentElement});
 w.HTMLElement.prototype.scrollBy=function({left,top}){this.scrollLeft+=left;this.scrollTop+=top;};
 let paused=false,time=0;
 Object.defineProperties(w.HTMLMediaElement.prototype,{paused:{get:()=>paused},currentTime:{get:()=>time,set:v=>time=v},duration:{get:()=>100}});
 w.HTMLMediaElement.prototype.pause=function(){paused=true;};w.HTMLMediaElement.prototype.play=function(){paused=false;return Promise.resolve();};
 w.eval(fs.readFileSync(path.join(__dirname,"../extension/page-handler.js"),"utf8"));
 const command=(args)=>w.__betterWinControlPage.command({...args,deadlineUnixMs:Date.now()+10000});
 return {dom,w,command};
}
const nodeFor=(o,name)=>o.elements.find(e=>e.name===name);
test("Unicode form input applies value, emits untrusted events, verifies and invalidates observation",async()=>{const f=fixture();try{const o=await f.command({op:"observe"});const input=f.w.document.querySelector("input");const events=[];input.addEventListener("input",e=>events.push({trusted:e.isTrusted,data:e.data}));const a=await f.command({op:"input",documentId:o.documentId,observationId:o.observationId,action:"set_value",elementId:nodeFor(o,"Notes").id,value:"مرحبا 👋"});assert.equal(input.value,"مرحبا 👋");assert.deepEqual(events,[{trusted:false,data:"مرحبا 👋"}]);assert.equal((await f.command({op:"verify",actionId:a.actionId})).effectVerified,true);assert.equal((await f.command({op:"input",documentId:o.documentId,observationId:o.observationId,action:"set_value",elementId:nodeFor(o,"Notes").id,value:"reuse"})).error.code,"stale_page_observation");}finally{f.dom.window.close();}});
test("media pause and seek report state independently",async()=>{const f=fixture();try{for(const [action,extra] of [["media_pause",{}],["media_seek",{seconds:42}]]){const o=await f.command({op:"observe"});const a=await f.command({op:"input",documentId:o.documentId,observationId:o.observationId,elementId:nodeFor(o,"Movie").id,action,...extra});assert.equal(a.submitted,true);assert.equal((await f.command({op:"verify",actionId:a.actionId})).effectVerified,true);}}finally{f.dom.window.close();}});
test("generic click never claims verified page outcome",async()=>{const f=fixture();try{let clicks=0;f.w.document.querySelector("button").addEventListener("click",()=>clicks++);const o=await f.command({op:"observe"});const a=await f.command({op:"input",documentId:o.documentId,observationId:o.observationId,elementId:nodeFor(o,"Apply").id,action:"click"});assert.equal(clicks,1);assert.equal(a.trustedInput,false);assert.equal((await f.command({op:"verify",actionId:a.actionId})).effectVerified,null);}finally{f.dom.window.close();}});
test("changed value or removed node rejects stale target",async()=>{const f=fixture();try{let o=await f.command({op:"observe"});f.w.document.querySelector("input").value="user changed";let r=await f.command({op:"input",documentId:o.documentId,observationId:o.observationId,elementId:nodeFor(o,"Notes").id,action:"set_value",value:"overwrite"});assert.equal(r.error.code,"stale_element");o=await f.command({op:"observe"});f.w.document.querySelector("button").remove();r=await f.command({op:"input",documentId:o.documentId,observationId:o.observationId,elementId:nodeFor(o,"Apply").id,action:"click"});assert.equal(r.error.code,"stale_element");}finally{f.dom.window.close();}});
test("password pages and sensitive fields excluded",async()=>{const f=fixture('<input type="password" value="secret">');try{assert.equal((await f.command({op:"observe"})).error.code,"protected_page");}finally{f.dom.window.close();}const g=fixture('<input name="apiToken" value="secret"><input aria-label="Notes">');try{const o=await g.command({op:"observe"});assert.equal(JSON.stringify(o).includes("secret"),false);assert.equal(o.elements.some(e=>e.name==="Notes"),true);}finally{g.dom.window.close();}});
test("wrong document ID, expired command and unsupported physical input fail closed",async()=>{const f=fixture();try{const o=await f.command({op:"observe"});assert.equal((await f.command({op:"input",documentId:"wrong",observationId:o.observationId,elementId:nodeFor(o,"Notes").id,action:"set_value",value:"x"})).error.code,"stale_page_observation");assert.equal((await f.w.__betterWinControlPage.command({op:"observe",deadlineUnixMs:Date.now()-1})).error.code,"deadline_expired");assert.equal((await f.command({op:"input",documentId:o.documentId,observationId:o.observationId,elementId:nodeFor(o,"Notes").id,action:"key_down",value:"A"})).error.code,"unsupported_element_action");}finally{f.dom.window.close();}});
